**Table of contents**<a id='toc0_'></a>    
- [Initializing a tensor](#toc1_)    
- [Directly from data](#toc2_)    
- [Operations on tensors](#toc3_)    
- [Single-element tensors](#toc4_)    
- [In-place operations](#toc5_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [ ]:
import torch
import numpy as np

# <a id='toc1_'></a>[Initializing a tensor](#toc0_)

In [2]:
# 1. Directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
# 2. From a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

# numpy 'np_array' and tensor 'x_np' share the same memory
# Torsor 和 NumPy 数组通常可以通过一个名为 bridge-to-np-label 的功能共享相同的底层内存地址，从而消除了复制数据的需要
# tensors and NumPy arrays can often share the same underlying memory address with a capability called bridge-to-np-label, which eliminates the need to copy data
np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [4]:
# 3. From another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6591, 0.1059],
        [0.4837, 0.5572]]) 



In [5]:
# 4. With random or constant values
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9468, 0.8580, 0.3887],
        [0.0157, 0.5881, 0.4200]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# <a id='toc2_'></a>[Directly from data](#toc0_)
Tensor attributes describe their shape, data type, and the device on which they are stored.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# <a id='toc3_'></a>[Operations on tensors](#toc0_)

- There are more than 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (such as transposing, indexing, and slicing).
- a comprehensive description [here](https://pytorch.org/docs/stable/torch.html)
- By default, tensors are created on the CPU. 
- Tensors can also be computed to GPUs; to do that, you need to move them using the .to method (after checking for GPU availability).


In [8]:
# We move our tensor to the GPU if available
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

False


# <a id='toc4_'></a>[Single-element tensors](#toc0_)

- If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[5.3235, 5.8003, 5.7012, 5.3880],
        [5.2322, 5.2198, 5.2325, 5.1057],
        [5.6465, 5.2133, 5.3477, 5.5309]]) tensor(64.7416)
64.74163818359375 <class 'float'>


# <a id='toc5_'></a>[In-place operations](#toc0_)

- Operations that store the result into the operand are called in-place.
- They are denoted by a _ suffix
- example: x.copy_(y), x.t_(), will change x

.. warning:: 注意：就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为它们会立即丢失历史记录。因此，不鼓励使用它们。

In [9]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.3235, 0.8003, 0.7012, 0.3880],
        [0.2322, 0.2198, 0.2325, 0.1057],
        [0.6465, 0.2133, 0.3477, 0.5309]]) 

tensor([[5.3235, 5.8003, 5.7012, 5.3880],
        [5.2322, 5.2198, 5.2325, 5.1057],
        [5.6465, 5.2133, 5.3477, 5.5309]])
