tensor([-2.4076, -1.4076, -0.4076])


# torch.nn.functional.log_softmax函数

In [3]:
import torch
import torch.nn.functional as F

# 定义输入向量
input_vector = torch.tensor([1.0, 2.0, 3.0])

# 使用 LogSoftmax 激活函数
# 将输入的向量进行 softmax 操作后再取对数，即对 softmax 的结果进行对数变换
output = F.log_softmax(input_vector, dim=0)

# 打印结果
print(output)


tensor([-2.4076, -1.4076, -0.4076])


# torch.nn.functional.softmax函数

In [2]:
import torch
import torch.nn.functional as F

# 假设有一个输入张量
input_tensor = torch.tensor([1.0, 2.0, 3.0])

# 使用 softmax 函数对输入张量进行处理
output = F.softmax(input_tensor, dim=0)

# 打印输出结果
print(output)


tensor([0.0900, 0.2447, 0.6652])
